salatino_cms:
    resource: "@SalatinoCMSBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

salatino_site:
    resource: "@SalatinoSiteBundle/Controller/"
    type:     annotation
    prefix:   /