services:
#    prime_cms.example:
#        class: SalatinoCMSBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    prime_cms.form.registration:
        class: SalatinoCMSBundle\Form\RegistrationType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: fos_user_registration }

    cms.form:
        class: SalatinoCMSBundle\Services\FormBuilder
        arguments: [ '@router', '@doctrine', '@form.factory' ]

    cms.model:
        class: SalatinoCMSBundle\Services\ModelFactory
        arguments: [ '@router', '@doctrine', '@request_stack', '%kernel.root_dir%' ]
