services:

    salatino_cms.form.registration:
        class: Salatino\CMSBundle\Form\RegistrationType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: fos_user_registration }

    cms.form:
        class: Salatino\CMSBundle\Services\FormBuilder
        arguments: [ '@router', '@doctrine', '@form.factory' ]

    cms.model:
        class: Salatino\CMSBundle\Services\ModelFactory
        arguments: [ '@router', '@doctrine', '@request_stack', '%kernel.root_dir%' ]
